=== sampaiodias/mf-2018/aula-7/dto/src/test/resources/json-schema/Endereco.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "id",
    "bairro",
    "distrito",
    "cep",
    "caixaPostal",
    "codigoMunicipio",
    "codigoEstado",
    "codigoPais",
    "codigoTipo",
    "dataInicio",
    "dataFim",
    "linhas"
  ],
  "properties": {
    "id": {
      "$id": "#/properties/id",
      "type": "integer",
      "title": "The Id Schema",
      "default": 0,
      "examples": [
        65
      ]
    },
    "bairro": {
      "$id": "#/properties/bairro",
      "type": "string",
      "title": "The Bairro Schema",
      "default": "",
      "examples": [
        "BAIRRO TESTE"
      ],
      "pattern": "^(.*)$"
    },
    "distrito": {
      "$id": "#/properties/distrito",
      "type": "string",
      "title": "The Distrito Schema",
      "default": "",
      "examples": [
        "DISTRITO TESTE"
      ],
      "pattern": "^(.*)$"
    },
    "cep": {
      "$id": "#/properties/cep",
      "type": "string",
      "title": "The Cep Schema",
      "default": "",
      "examples": [
        "12345-678"
      ],
      "pattern": "^(.*)$"
    },
    "caixaPostal": {
      "$id": "#/properties/caixaPostal",
      "type": "string",
      "title": "The Caixapostal Schema",
      "default": "",
      "examples": [
        "12345"
      ],
      "pattern": "^(.*)$"
    },
    "codigoMunicipio": {
      "$id": "#/properties/codigoMunicipio",
      "type": "integer",
      "title": "The Codigomunicipio Schema",
      "default": 0,
      "examples": [
        123
      ]
    },
    "codigoEstado": {
      "$id": "#/properties/codigoEstado",
      "type": "string",
      "title": "The Codigoestado Schema",
      "default": "",
      "examples": [
        "GO"
      ],
      "pattern": "^(.*)$"
    },
    "codigoPais": {
      "$id": "#/properties/codigoPais",
      "type": "integer",
      "title": "The Codigopais Schema",
      "default": 0,
      "examples": [
        55
      ]
    },
    "codigoTipo": {
      "$id": "#/properties/codigoTipo",
      "type": "integer",
      "title": "The Codigotipo Schema",
      "default": 0,
      "examples": [
        1234
      ]
    },
    "dataInicio": {
      "$id": "#/properties/dataInicio",
      "type": "object",
      "title": "The Datainicio Schema",
      "required": [
        "data",
        "acuracia"
      ],
      "properties": {
        "data": {
          "$id": "#/properties/dataInicio/properties/data",
          "type": "string",
          "title": "The Data Schema",
          "default": "",
          "examples": [
            "20181114"
          ],
          "pattern": "^(.*)$"
        },
        "acuracia": {
          "$id": "#/properties/dataInicio/properties/acuracia",
          "type": "string",
          "title": "The Acuracia Schema",
          "default": "",
          "examples": [
            "Acurado"
          ],
          "pattern": "^(.*)$"
        }
      }
    },
    "dataFim": {
      "$id": "#/properties/dataFim",
      "type": "object",
      "title": "The Datafim Schema",
      "required": [
        "data",
        "acuracia"
      ],
      "properties": {
        "data": {
          "$id": "#/properties/dataFim/properties/data",
          "type": "string",
          "title": "The Data Schema",
          "default": "",
          "examples": [
            "20181114"
          ],
          "pattern": "^(.*)$"
        },
        "acuracia": {
          "$id": "#/properties/dataFim/properties/acuracia",
          "type": "string",
          "title": "The Acuracia Schema",
          "default": "",
          "examples": [
            "Acurado"
          ],
          "pattern": "^(.*)$"
        }
      }
    },
    "linhas": {
      "$id": "#/properties/linhas",
      "type": "array",
      "title": "The Linhas Schema",
      "items": {
        "$id": "#/properties/linhas/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "linha",
          "ordem"
        ],
        "properties": {
          "linha": {
            "$id": "#/properties/linhas/items/properties/linha",
            "type": "string",
            "title": "The Linha Schema",
            "default": "",
            "examples": [
              "A"
            ],
            "pattern": "^(.*)$"
          },
          "ordem": {
            "$id": "#/properties/linhas/items/properties/ordem",
            "type": "integer",
            "title": "The Ordem Schema",
            "default": 0,
            "examples": [
              123
            ]
          }
        }
      }
    }
  }
}

=== sampaiodias/mf-2018/aula-7/dto/src/test/resources/json/Endereco.json
{
  "id": 65,
  "bairro": "BAIRRO TESTE",
  "distrito": "DISTRITO TESTE",
  "cep": "12345-678",
  "caixaPostal": "12345",
  "codigoMunicipio": 123,
  "codigoEstado": "GO",
  "codigoPais": 55,
  "codigoTipo": 1234,
  "dataInicio": {
    "data": "20181114",
    "acuracia": "Acurado"
  },
  "dataFim": {
    "data": "20181114",
    "acuracia": "Acurado"
  },
  "linhas": [
    {
      "linha": "A",
      "ordem": 123
    }
  ]
}
